# Generated by Django 2.0.4 on 2019-02-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    def apply_migration(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        db_alias = schema_editor.connection.alias
        Group.objects.using(db_alias).get_or_create(name='Admin')
        Group.objects.using(db_alias).get_or_create(name='Agent')
        Group.objects.using(db_alias).get_or_create(name='Export')


    def revert_migration(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Group.objects.filter(
            name__in=[
                u'Admin',
                u'Agent',
                u'Export',
            ]
        ).delete()

    dependencies = [
        ('user_profiles', '0002_admin'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
