# Generated by Django 2.0.4 on 2018-11-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0005_importrequest_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=255, verbose_name='HS CODE')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('height', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Height')),
                ('width', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Width')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Depth')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Weight')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('time_production', models.CharField(max_length=255, verbose_name='Production Time')),
                ('moq', models.CharField(max_length=255, verbose_name='MOQ')),
                ('total_pieces', models.IntegerField(verbose_name='TOTAL pcs')),
                ('pieces_carton', models.IntegerField(verbose_name='PCS/carton')),
                ('box_height', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Box Height')),
                ('box_width', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Box Width')),
                ('box_depth', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Box Depth')),
                ('total_cbm', models.IntegerField(verbose_name='Total CBM')),
                ('fob_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='FOB PRICE / usd')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('supplier_information', models.TextField(verbose_name='Supplier Data')),
                ('import_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importing.ImportRequest')),
            ],
        ),
    ]
