# Generated by Django 2.0.4 on 2018-11-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0006_importresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.TextField(default='None', verbose_name='Comments'),
            preserve_default=False,
        ),
    ]
