# Generated by Django 2.0.4 on 2018-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0007_auto_20181106_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importresponse',
            name='fob_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='FOB PRICE / USD'),
        ),
        migrations.AlterField(
            model_name='importresponse',
            name='time_production',
            field=models.IntegerField(verbose_name='Production Time'),
        ),
        migrations.AlterField(
            model_name='importresponse',
            name='total_cbm',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total CBM'),
        ),
    ]
