# Generated by Django 2.0.4 on 2018-11-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0008_auto_20181106_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrequest',
            name='comments',
            field=models.TextField(default='None', verbose_name='Comments'),
            preserve_default=False,
        ),
    ]
