# Generated by Django 2.0.4 on 2018-12-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0009_importrequest_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='CBM')),
                ('measurements', models.TextField(max_length=255, verbose_name='Medidas')),
                ('ton', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ton')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
            ],
        ),
    ]
