# Generated by Django 2.0.4 on 2018-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0011_starting_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='measurements',
            field=models.CharField(max_length=255, verbose_name='Medidas'),
        ),
    ]
