# Generated by Django 2.0.4 on 2019-02-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0013_auto_20190210_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='importresponse',
            name='container_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimate'),
        ),
    ]
