# Generated by Django 2.0.4 on 2019-02-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_auto_20190210_1939'),
        ('importing', '0014_importresponse_container_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrequest',
            name='export_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profiles.Agent', verbose_name='Export Agent'),
        ),
    ]
